apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pvc
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: django
  labels:
    app: django
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 20
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - image: guddn1963/django:3.2
        name: django-app
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          initialDelaySeconds: 10
          httpGet:
            path: /
            port: 8080
        livenessProbe:
          periodSeconds: 3
          initialDelaySeconds: 10
          httpGet:
            path: /
            port: 8080
        volumeMounts:
        - name: django-persistent-storage
          mountPath: /mysite/datastore
      volumes:
      - name: django-persistent-storage
        persistentVolumeClaim:
          claimName: django-pvc
