apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: wordpress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
spec:
  defaultBackend: 
    service:
      name: wordpress
      port:
       number: 80
  rules:
  - host: www.vaccinbook.com
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend: 
          service:
            name: wordpress
            port:
              number: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-data-pvc01
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: webapp-data-pv01
  storageClassName: ''
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-data-pv01
  labels:
    app: wordpress
spec:
  capacity:
    storage: 20Gi
  accessModes:    
  - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain  
  nfs:  
    path: /apps/datastore/
    server: 192.168.56.11
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 4
  strategy:  
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  
      maxSurge: 5
  minReadySeconds: 20
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        readinessProbe:
          periodSeconds: 5
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            cpu: 50m
            memory: 5Mi
          limits:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: webapp-data-pvc01
